# Generated by Django 6.0.4 on 2026-04-16 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('oab_number', models.CharField(max_length=20)),
                ('oab_state', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=20)),
                ('office_address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('practice_areas', models.JSONField(default=list)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('average_monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('average_monthly_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('financial_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_employees', models.BooleanField(default=False)),
                ('office_type', models.CharField(choices=[('HOME', 'HOME'), ('PHYSICAL', 'PHYSICAL')], default='HOME', max_length=20)),
                ('income_variability', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='HIGH', max_length=20)),
                ('has_bank_connected', models.BooleanField(default=False)),
                ('goal_type', models.CharField(choices=[('SURVIVAL', 'SURVIVAL'), ('STABILITY', 'STABILITY'), ('GROWTH', 'GROWTH')], default='STABILITY', max_length=20)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
